_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  VGG:
    OUT_FEATURES: ["vgg_block1", "vgg_block2", "vgg_block3", "vgg_block4", "vgg_block5"]
  ROI_HEADS:
    NUM_CLASSES: 8
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (30000,)
  MAX_ITER: 30000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 1000
  REFERENCE_BATCH_SIZE: 16
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("VOC2007_citytrain",)
  TRAIN_UNLABEL: ("VOC2007_foggytrain_0.02",)
  TEST: ("VOC2007_foggyval_0.02",)
UNSUPNET:
  Trainer: "pt"
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 4000
  EMA_KEEP_RATE: 0.9996
  SOURCE_LOSS_WEIGHT: 1.0
  TARGET_UNSUP_LOSS_WEIGHT: 1.0
  GUASSIAN: True
  EFL: True
  EFL_LAMBDA: [0.5,0.5]
  TAU: [0.25,0.25]
  CONTRASTIVE: True
  CONTRASTIVE_LOSS_WEIGHT: 0.05
  BBOX_THRESHOLD: 0.6
  NUM_CLASSES: 8
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/c2f_0.02/"
