MODEL:
  META_ARCHITECTURE: "GuassianGeneralizedRCNN"
  MASK_ON: False
  WEIGHTS: ''
  BACKBONE:
    NAME: "build_vgg_backbone"
  VGG:
    DEPTH: 16
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[128, 256, 512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  PROPOSAL_GENERATOR:
    NAME: "GuassianRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    IN_FEATURES: ['vgg_block5']
    HEAD_NAME: 'GuassianRPNHead'
  ROI_HEADS:
    NAME: "GuassianROIHead"
    IN_FEATURES: ['vgg_block5']
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    FC_DIM: 1024
    POOLER_RESOLUTION: 7
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
VERSION: 2
